# CI name
name: Run Linting and Testing

# The on key is used to define when
# the CI should be triggered, aka Event
on: [push, pull_request]

jobs:
  # Job name
  suite:
    # OS of the runner
    runs-on: ubuntu-latest
    # A step is an individual task that can run commands in a job
    # and share the same runner.
    # Each step can run a ready-to-use action or a bash command
    steps:
      # Runner meaningful name
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - run: npm install
      
      - name: Run Build
      - run: npm run build
      
      - name: Run Linting
      - run: npm run lint
      
      - name: Run Testing
      - run: CI=true npm run test:ci
