# CI name
name: Run Linting and Testing

# The on key is used to define when
# the CI should be triggered, aka Event
on: [push, pull_request]

jobs:
  suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_GOOGLE_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}

      - name: Setup Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
          cache: 'npm'
      - run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Testing
        run: CI=true npm run test:ci